`timescale 1ns / 1ps

module tb_conv2d_accel();

    // Configuration parameters 
    parameter H = 16;
    parameter W = 16;
    parameter K = 3;
    parameter OUT_H = H - K + 1;
    parameter OUT_W = W - K + 1;

    // System signals
    reg clk;
    reg rst;

    // Bus interface signals with the Wrapper
    reg         wr_en;
    reg  [15:0] wr_addr;
    reg  [7:0]  wr_data;
    wire        wr_ready;

    reg         rd_en;
    reg  [15:0] rd_addr;
    wire [7:0]  rd_data;
    wire        rd_valid;

    // Temporary memory in Testbench to hold data from Hex files
    reg [7:0] tb_input_map [0:(H*W)-1];
    reg [7:0] tb_kernel    [0:(K*K)-1];
    reg [7:0] tb_expected  [0:(OUT_H*OUT_W)-1];

    // Instantiate Module 3: IP Wrapper
    conv2d_accel #(
        .H(H), .W(W), .K(K), .DATA_W(8), .ACC_W(32), .ADDR_W(16)
    ) dut (
        .clk(clk), .rst(rst),
        .wr_en(wr_en), .wr_addr(wr_addr), .wr_data(wr_data), .wr_ready(wr_ready),
        .rd_en(rd_en), .rd_addr(rd_addr), .rd_data(rd_data), .rd_valid(rd_valid)
    );

    // Generate Clock signal (10ns period -> 100MHz)
    always #5 clk = ~clk;

    // ---------------------------------------------------------
    // TASK: Write data to Bus
    // ---------------------------------------------------------
    task bus_write(input [15:0] addr, input [7:0] data);
        begin
            @(posedge clk);
            wr_en   <= 1;
            wr_addr <= addr;
            wr_data <= data;
            
            // Wait until the Wrapper asserts wr_ready = 1
            wait(wr_ready == 1'b1);
            @(posedge clk);
            wr_en <= 0; // Disable write signal
        end
    endtask

    // ---------------------------------------------------------
    // TASK: Read data from Bus 
    // ---------------------------------------------------------
    task bus_read(input [15:0] addr, output [7:0] data);
        begin
            @(posedge clk);
            rd_en   <= 1;
            rd_addr <= addr;
            
            // Wait for SRAM latency (until Wrapper asserts rd_valid = 1)
            wait(rd_valid == 1'b1);
            @(posedge clk);
            data = rd_data; // Get data
            rd_en <= 0;     // Disable read signal

            wait(rd_valid == 1'b0);
        end
    endtask

    // ---------------------------------------------------------
    // MAIN TEST SEQUENCE
    // ---------------------------------------------------------
    integer i;
    reg [7:0] read_val;
    reg [7:0] status;
    integer errors;

    initial begin
        // Initialize waveform dumping to view in GTKWave
        $dumpfile("tb_conv.vcd");
        $dumpvars(0, tb_conv2d_accel);

        // 1. Load data from Hex files generated by Python
        $readmemh("input_feature_map.txt", tb_input_map);
        $readmemh("kernel.txt", tb_kernel);
        $readmemh("expected_output.txt", tb_expected);

        // 2. Set initial values and System Reset
        clk = 0; wr_en = 0; rd_en = 0; errors = 0;
        rst = 1;
        #20 rst = 0; // Deassert reset after 20ns
        #10;

        $display("=== STARTING CONVOLUTION TEST ===");

        // 3. Load Input Feature Map into Input SRAM (0x0000)
        $display("Loading Input SRAM...");
        for (i = 0; i < H*W; i = i + 1) begin
            bus_write(16'h0000 + i, tb_input_map[i]);
        end

        // 4. Load Kernel into Kernel SRAM (0x0100)
        $display("Loading Kernel SRAM...");
        for (i = 0; i < K*K; i = i + 1) begin
            bus_write(16'h0100 + i, tb_kernel[i]);
        end

        // 5. Send Start signal (Write 1 to Control Register 0x1000)
        $display("Starting Convolution Engine...");
        bus_write(16'h1000, 8'h01);

        // 6. Polling: Continuously read Status Register (0x1004) to wait for completion
        status = 8'h00;
        
        while (status !== 8'h01) begin
            bus_read(16'h1004, status);
        end
        $display("Engine Done! Checking results...");

        // (Optional) Read elapsed cycle count
        $display("Cycles taken: %d", dut.cycle_count);

        // 7. Read Output SRAM (0x2000) and compare with Expected
        for (i = 0; i < OUT_H*OUT_W; i = i + 1) begin
            bus_read(16'h2000 + i, read_val);
            if (read_val !== tb_expected[i]) begin
                $display("ERROR at pixel %d: Expected %h, Got %h", i, tb_expected[i], read_val);
                errors = errors + 1;
            end
        end

        // 8. PASS / FAIL Conclusion
        $display("=================================");
        if (errors == 0)
            $display(">> TEST PASS! All pixels match Golden Reference.");
        else
            $display(">> TEST FAIL! Found %d errors.", errors);
        $display("=================================");

        $finish; // End simulation
    end

endmodule