# -*- coding: utf-8 -*-
"""projectpnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JljX7jt4w3EMjBDnVF9ny2CPV9lF6aXl
"""

import numpy as np
import matplotlib.pyplot as plt
import torch
from torchvision import datasets, transforms

def conv2d(input_map, kernel):
    """
    Task A: 2D convolution from scratch using nested loops.
    input_map: H x W array
    kernel: K x K array
    returns: (H-K+1) x (W-K+1) array
    """
    H, W = input_map.shape
    K, _ = kernel.shape
    out_h = H - K + 1
    out_w = W - K + 1

    output_map = np.zeros((out_h, out_w))

    for r in range(out_h):
        for c in range(out_w):
            # Extract the KxK patch
            patch = input_map[r:r+K, c:c+K]
            # Element-wise multiply and sum
            output_map[r, c] = np.sum(patch * kernel)

    return output_map

# Verification with hand-computable example from specification
input_test = np.array([
    [1, 2, 3, 0, 1, 2],
    [0, 1, 2, 3, 0, 1],
    [1, 0, 1, 2, 3, 0],
    [2, 1, 0, 1, 2, 3],
    [0, 1, 2, 0, 1, 2],
    [1, 0, 1, 1, 0, 1]
])
kernel_test = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

result = conv2d(input_test, kernel_test)
print("Test Output[0][0]:", result[0, 0], "(Expected: -4.0)")

"""### Task A: 2D Convolution from Scratch
The code above implements the `conv2d` function using nested loops to slide a $K \times K$ kernel over an $H \times W$ input map. This manually calculates the dot product for each window, fulfilling the requirement to avoid high-level library functions like `np.convolve`. We verified it using the $6 \times 6$ example provided in the project specifications, confirming that `output[0][0]` correctly yields -4.
"""

import torch.nn as nn

# Task B: Load MNIST and prepare a kernel from a model
transform = transforms.Compose([transforms.ToTensor()])
mnist_train = datasets.MNIST(root='./data', train=True, download=True, transform=transform)

# Get one image
image, label = mnist_train[0]
full_image_np = image.squeeze().numpy()

# Slice the center 16x16 region (from index 6 to 22)
image_np = full_image_np[6:22, 6:22]

# Define the recommended architecture: 1 conv layer + 1 fully connected layer
class SimpleMNIST(nn.Module):
    def __init__(self):
        super(SimpleMNIST, self).__init__()
        # First conv layer: 1 input channel, 8 output channels, 3x3 kernel
        self.conv1 = nn.Conv2d(1, 8, kernel_size=3, padding=0)
        self.fc = nn.Linear(8 * 26 * 26, 10)

    def forward(self, x):
        x = torch.relu(self.conv1(x))
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

# Initialize the model and extract the first kernel (out_channel 0)
model = SimpleMNIST()
weights = model.conv1.weight.data.numpy()
kernel_demo = weights[0, 0, :, :]

# Run convolution on float32 data
conv_output_float = conv2d(image_np, kernel_demo)

# Visualization
fig, axes = plt.subplots(1, 3, figsize=(12, 4))
axes[0].imshow(image_np, cmap='gray')
axes[0].set_title("16x16 Input")
axes[1].imshow(kernel_demo, cmap='gray')
axes[1].set_title("3x3 Kernel")
axes[2].imshow(conv_output_float, cmap='gray')
axes[2].set_title("14x14 Conv Output")
plt.show()

print("Input Shape:", image_np.shape)
print("Extracted Kernel Values:\n", kernel_demo)

"""### Task B: Data Preparation
In this section, we load the MNIST dataset using `torchvision`. We extract a $16 \times 16$ grayscale digit region and define a $3 \times 3$ kernel. This setup mimics the first layer of a CNN, providing the data needed to generate golden reference files for hardware simulation.
"""

def quantize_to_int8(data):
    """
    Task C: Quantize floating-point array to 8-bit signed integers.
    Determines a scaling factor, rounds, and clips to [-128, 127].
    """
    max_val = np.max(np.abs(data))
    if max_val == 0:
        return data.astype(np.int8), 1.0

    # Scaling factor to fit max_val into 127
    scale = 127.0 / max_val
    quantized = np.round(data * scale)
    quantized = np.clip(quantized, -128, 127).astype(np.int8)

    return quantized, scale

# Quantize input and kernel
input_int8, input_scale = quantize_to_int8(image_np)
kernel_int8, kernel_scale = quantize_to_int8(kernel_demo)

# Run convolution on quantized data
# Simulating hardware: accumulate in int32
conv_output_int32 = conv2d(input_int8.astype(np.int32), kernel_int8.astype(np.int32))
conv_output_int8 = (conv_output_int32.astype(np.int32) & 0xFF).astype(np.int8)

# Quantization Error Analysis (Task C Requirement)
reconstructed_float = conv_output_int32 / (input_scale * kernel_scale)
quant_error = np.abs(conv_output_float - reconstructed_float)
max_error = np.max(quant_error)
mean_error = np.mean(quant_error)

# Visualization for Comparison
fig, axes = plt.subplots(1, 2, figsize=(10, 5))
axes[0].imshow(conv_output_float, cmap='gray')
axes[0].set_title("Original Float32 Convolution")
axes[1].imshow(conv_output_int8, cmap='gray')
axes[1].set_title("Quantized Int8 (HW Output)")
plt.show()

print(f"Input scale: {input_scale:.4f}, Kernel scale: {kernel_scale:.4f}")
print(f"Maximum Absolute Quantization Error: {max_error:.6f}")
print(f"Mean Absolute Quantization Error: {mean_error:.6f}")

# Print center regions for verification
center = conv_output_int8.shape[0] // 2
print(f"\nFloat32 Convolution Result (Center 5x5 at {center}):\n", conv_output_float[center-2:center+3, center-2:center+3])
print(f"\nInt8 Convolution Result (Center 5x5 at {center}):\n", conv_output_int8[center-2:center+3, center-2:center+3])

"""### Task C: 8-bit Quantization
Since hardware accelerators are optimized for integers, we convert our floating-point image and weights into 8-bit signed integers ($[-128, 127]$). We determine a scaling factor based on the maximum absolute value in the data. The convolution is then performed using these integers, simulating how the Verilog MAC (Multiply-Accumulate) unit will process the data.
"""

def to_hex_string(val, bits=8):
    """Converts a signed integer to a 2's complement hex string."""
    val_int = int(val)
    if val_int < 0:
        val_int = (1 << bits) + val_int
    format_str = f"0{bits // 4}x"
    return format(val_int, format_str).upper()

def save_to_hex(filename, data, bits=8):
    """Task D: Generate hex files with rows matching the input data structure for $readmemh."""
    with open(filename, 'w') as f:
        for row in data:
            # Convert each value in the row to hex and join with spaces
            hex_row = " ".join([to_hex_string(val, bits) for val in row])
            f.write(hex_row + '\n')
    print(f"Saved {filename}")

# Using variables already calculated in Task C cells
# Generate the four required files
save_to_hex('input_feature_map.txt', input_int8, bits=8)
save_to_hex('kernel.txt', kernel_int8, bits=8)
save_to_hex('expected_output.txt', conv_output_int8, bits=8)
save_to_hex('expected_output_full32.txt', conv_output_int32.astype(np.int32), bits=32)

print("\nSoftware Golden Reference Generation Complete.")
print(f"Input Feature Map shape: {input_int8.shape}")
print(f"Kernel shape: {kernel_int8.shape}")
print(f"Output Feature Map shape: {conv_output_int8.shape}")

"""### Task D: Hex File Generation for Verilog
To bridge the gap between Python and Verilog, we generate `.txt` files containing hexadecimal strings. The `to_hex_string` function ensures that negative numbers are correctly represented in 2's complement (e.g., -1 becomes `FF`). These files (`input_feature_map.txt`, `kernel.txt`, and `expected_output.txt`) will be loaded into SRAMs in your Verilog testbench using the `$readmemh` command.
"""